// Generated by tools/vlm_durations.py from the punchout speech ROM: the
// number of VLM5030 frames in each indirect phrase (table byte = index*2).
// Frames, not time: the RTL applies the speed parameter the game latches.
localparam logic [11:0] VLM_FRAMES [0:127] = '{
    12'd18, //   0: table byte 00, ok
    12'd49, //   1: table byte 02, ok
    12'd14, //   2: table byte 04, ok
    12'd1, //   3: table byte 06, ok
    12'd54, //   4: table byte 08, ok
    12'd117, //   5: table byte 0a, ok
    12'd134, //   6: table byte 0c, ok
    12'd42, //   7: table byte 0e, ok
    12'd260, //   8: table byte 10, ok
    12'd191, //   9: table byte 12, ok
    12'd134, //  10: table byte 14, ok
    12'd80, //  11: table byte 16, ok
    12'd46, //  12: table byte 18, ok
    12'd44, //  13: table byte 1a, ok
    12'd21, //  14: table byte 1c, ok
    12'd37, //  15: table byte 1e, ok
    12'd25, //  16: table byte 20, ok
    12'd17, //  17: table byte 22, ok
    12'd28, //  18: table byte 24, ok
    12'd12, //  19: table byte 26, ok
    12'd27, //  20: table byte 28, ok
    12'd27, //  21: table byte 2a, ok
    12'd39, //  22: table byte 2c, ok
    12'd35, //  23: table byte 2e, ok
    12'd40, //  24: table byte 30, ok
    12'd33, //  25: table byte 32, ok
    12'd78, //  26: table byte 34, ok
    12'd108, //  27: table byte 36, ok
    12'd90, //  28: table byte 38, ok
    12'd68, //  29: table byte 3a, ok
    12'd115, //  30: table byte 3c, ok
    12'd120, //  31: table byte 3e, ok
    12'd119, //  32: table byte 40, ok
    12'd93, //  33: table byte 42, ok
    12'd102, //  34: table byte 44, ok
    12'd138, //  35: table byte 46, ok
    12'd155, //  36: table byte 48, ok
    12'd14, //  37: table byte 4a, ok
    12'd29, //  38: table byte 4c, ok
    12'd9, //  39: table byte 4e, ok
    12'd25, //  40: table byte 50, ok
    12'd63, //  41: table byte 52, ok
    12'd17, //  42: table byte 54, ok
    12'd17, //  43: table byte 56, ok
    12'd0, //  44: table byte 58, ran off the ROM
    12'd0, //  45: table byte 5a, ran off the ROM
    12'd0, //  46: table byte 5c, ran off the ROM
    12'd0, //  47: table byte 5e, ran off the ROM
    12'd0, //  48: table byte 60, ran off the ROM
    12'd0, //  49: table byte 62, ran off the ROM
    12'd174, //  50: table byte 64, ok
    12'd0, //  51: table byte 66, ran off the ROM
    12'd0, //  52: table byte 68, ran off the ROM
    12'd0, //  53: table byte 6a, ran off the ROM
    12'd0, //  54: table byte 6c, ran off the ROM
    12'd0, //  55: table byte 6e, ran off the ROM
    12'd0, //  56: table byte 70, ran off the ROM
    12'd0, //  57: table byte 72, ran off the ROM
    12'd0, //  58: table byte 74, ran off the ROM
    12'd0, //  59: table byte 76, ran off the ROM
    12'd0, //  60: table byte 78, ran off the ROM
    12'd0, //  61: table byte 7a, ran off the ROM
    12'd0, //  62: table byte 7c, ran off the ROM
    12'd0, //  63: table byte 7e, ran off the ROM
    12'd0, //  64: table byte 80, ran off the ROM
    12'd0, //  65: table byte 82, ran off the ROM
    12'd0, //  66: table byte 84, ran off the ROM
    12'd0, //  67: table byte 86, ran off the ROM
    12'd0, //  68: table byte 88, ran off the ROM
    12'd0, //  69: table byte 8a, ran off the ROM
    12'd0, //  70: table byte 8c, ran off the ROM
    12'd0, //  71: table byte 8e, ran off the ROM
    12'd0, //  72: table byte 90, ran off the ROM
    12'd0, //  73: table byte 92, ran off the ROM
    12'd0, //  74: table byte 94, ran off the ROM
    12'd0, //  75: table byte 96, ran off the ROM
    12'd23, //  76: table byte 98, ok
    12'd0, //  77: table byte 9a, ran off the ROM
    12'd0, //  78: table byte 9c, ok
    12'd0, //  79: table byte 9e, ok
    12'd0, //  80: table byte a0, ran off the ROM
    12'd0, //  81: table byte a2, ran off the ROM
    12'd0, //  82: table byte a4, ran off the ROM
    12'd0, //  83: table byte a6, ran off the ROM
    12'd0, //  84: table byte a8, ran off the ROM
    12'd0, //  85: table byte aa, ran off the ROM
    12'd0, //  86: table byte ac, ran off the ROM
    12'd0, //  87: table byte ae, ran off the ROM
    12'd0, //  88: table byte b0, ran off the ROM
    12'd0, //  89: table byte b2, ran off the ROM
    12'd0, //  90: table byte b4, ran off the ROM
    12'd0, //  91: table byte b6, ran off the ROM
    12'd0, //  92: table byte b8, ran off the ROM
    12'd0, //  93: table byte ba, ran off the ROM
    12'd0, //  94: table byte bc, ran off the ROM
    12'd0, //  95: table byte be, ran off the ROM
    12'd0, //  96: table byte c0, ran off the ROM
    12'd0, //  97: table byte c2, ran off the ROM
    12'd59, //  98: table byte c4, ok
    12'd54, //  99: table byte c6, ok
    12'd0, // 100: table byte c8, ran off the ROM
    12'd0, // 101: table byte ca, ok
    12'd15, // 102: table byte cc, ok
    12'd12, // 103: table byte ce, ok
    12'd1, // 104: table byte d0, ok
    12'd176, // 105: table byte d2, ok
    12'd1, // 106: table byte d4, ok
    12'd0, // 107: table byte d6, ran off the ROM
    12'd1, // 108: table byte d8, ok
    12'd0, // 109: table byte da, ran off the ROM
    12'd0, // 110: table byte dc, ran off the ROM
    12'd1, // 111: table byte de, ok
    12'd0, // 112: table byte e0, ran off the ROM
    12'd0, // 113: table byte e2, ran off the ROM
    12'd127, // 114: table byte e4, ok
    12'd0, // 115: table byte e6, ran off the ROM
    12'd0, // 116: table byte e8, ran off the ROM
    12'd92, // 117: table byte ea, ok
    12'd0, // 118: table byte ec, ran off the ROM
    12'd0, // 119: table byte ee, ran off the ROM
    12'd92, // 120: table byte f0, ok
    12'd0, // 121: table byte f2, ran off the ROM
    12'd0, // 122: table byte f4, ran off the ROM
    12'd92, // 123: table byte f6, ok
    12'd0, // 124: table byte f8, ran off the ROM
    12'd0, // 125: table byte fa, ran off the ROM
    12'd92, // 126: table byte fc, ok
    12'd0  // 127: table byte fe, ran off the ROM
};
