#!/usr/bin/env python3
"""Phrase lengths of the VLM5030 speech ROM, as the chip would time them.

A measurement tool: the game paces its display against the chip's BUSY line
(with BUSY never asserted, a knock-down phrase "finished" instantly and the
game ran its pre-bout blink cue in the middle of the gloat -- the black bar).
This walks the frames exactly as MAME's vlm5030.cpp does and lists each
phrase's length. The chip itself is rtl/po_vlm5030.sv now; the table this
emitted once fed an interim BUSY-only model.

  python3 tools/vlm_durations.py build/punchout.rom build/vlm_frames.svh   # listing + a table nobody includes now

Timing (vlm5030.cpp): ST high -> BSY high; ST low -> speech starts, and
every voiced frame lasts FR_SIZE=4 interpolation periods of frame_size
samples (2400 bps parameter, interp_step 1); a silent frame with command
byte c lasts ((c>>2)+1)*2 frames; after the end marker one more period, then
one sample, then BSY drops. frame_size comes from parameter bits 3-5:
speed table {40, 30, 20, 20, 40, 60, 50, 50}. Sample rate 3579545/440.
The table stores FRAMES per phrase; the RTL multiplies by the live speed.
"""
import sys

VLM_OFF, VLM_LEN = 0x56C00, 0x4000
FR_SIZE = 4

def phrase_frames(rom, table_byte):
    table = (table_byte & 0xfe) + ((table_byte & 1) << 8)
    addr = (rom[table] << 8) | rom[table + 1]
    frames = 0
    for _ in range(4096):
        if addr >= len(rom):
            return frames, addr, 'ran off the ROM'
        cmd = rom[addr]
        if cmd & 1:
            addr += 1
            if cmd & 2:
                return frames, addr, 'ok'
            frames += ((cmd >> 2) + 1) * 2
        else:
            frames += 1
            addr += 6
    return frames, addr, 'no end marker'

def main():
    image, out = sys.argv[1], sys.argv[2]
    data = open(image, 'rb').read()
    rom = data[VLM_OFF:VLM_OFF + VLM_LEN]
    rows = []
    for tb in range(0, 256, 2):          # even table bytes: 128 indirect phrases
        n, end, status = phrase_frames(rom, tb)
        rows.append((tb, n, end, status))
    with open(out, 'w') as f:
        f.write('// Generated by tools/vlm_durations.py from the punchout speech ROM: the\n'
                '// number of VLM5030 frames in each indirect phrase (table byte = index*2).\n'
                '// Frames, not time: the RTL applies the speed parameter the game latches.\n')
        f.write('localparam logic [11:0] VLM_FRAMES [0:127] = \'{\n')
        for i, (tb, n, end, status) in enumerate(rows):
            n = min(n, 4095) if status == 'ok' else 0
            f.write('    12\'d%d%s // %3d: table byte %02x, %s\n' % (n, ',' if i < 127 else ' ', i, tb, status))
        f.write('};\n')
    for tb, n, end, status in rows:
        if n:
            print('phrase %3d (byte %02x): %4d frames  %6.0f ms at speed 30, %6.0f ms at 40  [%s]' %
                  (tb // 2, tb, n, n * 4 * 30 / 8135.33 * 1000, n * 4 * 40 / 8135.33 * 1000, status))

if __name__ == '__main__':
    main()
